import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home.component';
import { GlobalTourComponent } from './pages/global-tour/global-tour.component';
import { ExhibitionComponent } from './pages/exhibition/exhibition.component';
import { CaribbeanConnectionsComponent } from './pages/caribbean-connections/caribbean-connections.component';
import { ExperienceComponent } from './pages/caribbean-connections/experience/experience.component';
import { AboutConnectionsComponent } from './pages/caribbean-connections/about-connections/about-connections.component';
import { ContactConnectionsComponent } from './pages/caribbean-connections/contact-connections/contact-connections.component';
import { ResidencyComponent } from './pages/residency/residency.component';
import { Residency2Component } from './pages/residency-2/residency-2.component';
import { FirstWaveChallengeComponent } from './pages/first-wave-challenge/first-wave-challenge.component';
import { SaintLuciaComponent } from './pages/saint-lucia/saint-lucia.component';
import { ContactComponent } from './pages/contact/contact.component';
import { AboutUsComponent } from './pages/about-us/about-us.component';
import { ContestComponent } from './pages/contest/contest.component';
import { ContestEntryComponent } from './pages/contest-entry/contest-entry.component';
import { CheckoutComponent } from './pages/checkout/checkout.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'global-tour', component: GlobalTourComponent },
  { path: 'exhibition', component: ExhibitionComponent },
  { path: 'caribbean-connections', component: CaribbeanConnectionsComponent },
  { path: 'caribbean-connections/experience', component: ExperienceComponent },
  { path: 'caribbean-connections/about-connections', component: AboutConnectionsComponent },
  { path: 'caribbean-connections/contact-connections', component: ContactConnectionsComponent },
  { path: 'residency', component: ResidencyComponent },
  { path: 'residency-2', component: Residency2Component },
  { path: 'first-wave-challenge', component: FirstWaveChallengeComponent },
  { path: 'saint-lucia', component: SaintLuciaComponent },
  { path: 'contact', component: ContactComponent },
  { path: 'about-us', component: AboutUsComponent },
  { path: 'contest', component: ContestComponent },
  { path: 'contest-entry/:id', component: ContestEntryComponent },
  { path: 'checkout/:contestId/:tierId', component: CheckoutComponent },
  { path: '**', redirectTo: '' },
];
